name: CS7643_deep_learning_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu130
      - torch
      - torchvision
      - numpy
      - pandas
      - imagehash
      - Pillow
      - matplotlib
      - kaggle
      - ipykernel
      - pyyaml
      - lightning
      - tensorboard
      - wandb
      - torchmetrics
      - seaborn
      - albumentations
      - opencv-python
      - scikit-learn

