## data arguments
experiment: eval
batch_size: 64
num_workers: 1
data_dir: data

## huggingface models to evaluate
repo_id: gatech-deep-learning-project
# cache_dir: .cache/huggingface/ (optional)
models:
  vgg19_se_attention_finetune: # name on huggingface
    ckpt_path: best-epoch=24-val_acc=0.9721.ckpt # path on huggingface
    # reduction: int (optional)
    attention_type: se # attention_type: se | softmax | cbam | self | None (optional)
  vgg19_cbam_finetune_aug:
    ckpt_path: best-epoch=18-val_acc=0.9741.ckpt
    attention_type: cbam
  vgg19_softmax_attention_finetune_aug:
    ckpt_path: best-epoch=12-val_acc=0.9741.ckpt
    attention_type: softmax
  vgg19_self_attention_finetune_aug:
    ckpt_path: best-epoch=27-val_acc=0.9761.ckpt
    attention_type: self