experiment: se_attention_finetune
epochs: 30
batch_size: 64
lr: 0.001
num_workers: 0
data_dir: data
model_checkpoint_path: checkpoints/vgg19_se_attention_finetune/best-epoch=24-val_acc=0.9721.ckpt
total_examples: 30
seed: 42