# training arguments
experiment: softmax_attention_finetune_aug
epochs: 30
batch_size: 64
lr: 0.001
num_workers: 0
data_dir: data

# gradcam arguments
generate_gradcam: True
checkpoint_path: None
total_examples: 3
seed: 42
