# training arguments
experiment: softmax_attention_finetune_aug
epochs: 30
batch_size: 64
lr: 0.001
num_workers: 0
data_dir: data

# gradcam arguments
generate_gradcam: True
model_checkpoint_path: checkpoints/vgg19_softmax_attention_finetune_aug/best-epoch=12-val_acc=0.9741.ckpt
total_examples: 30
seed: 42